GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imthc3BlciIsImlhdCI6MTc0Mzk0Njg4NCwiZXhwIjoxNzQzOTUwNDg0fQ.v6yuUt-PvrspX9dHodQwZ1mcPl1jQ4RLHOLvuqqafyE
###

POST http://localhost:3000/signup
content-Type: application/json

{
    "username": "kasper",
    "password": "123"
}

###

POST http://localhost:3000/login
content-Type: application/json

{
    "username": "kasper",
    "password": "123"
}